stages:
  - test
  - build
  - deploy
unity-test:
  script: "C:\\’Program Files’\\Unity\\Editor\\Unity.exe \
    -batchmode \
    -projectPath . \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml"
  stage: test
  tags:
    - unity
unity-build:
  script: "echo 'Building...'"
  stage: build
  tags:
    - unity
unity-deploy:
  script: "echo 'Deploying...'"
  stage: deploy
  tags:
    - unity
